/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProductsIndexRouteImport } from './routes/api/products/index'
import { Route as ApiProductsExpiringRouteImport } from './routes/api/products/expiring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIndexRoute = ApiProductsIndexRouteImport.update({
  id: '/api/products/',
  path: '/api/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsExpiringRoute = ApiProductsExpiringRouteImport.update({
  id: '/api/products/expiring',
  path: '/api/products/expiring',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/products/expiring': typeof ApiProductsExpiringRoute
  '/api/products/': typeof ApiProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/products/expiring': typeof ApiProductsExpiringRoute
  '/api/products': typeof ApiProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/products/expiring': typeof ApiProductsExpiringRoute
  '/api/products/': typeof ApiProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/products/expiring' | '/api/products/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/products/expiring' | '/api/products'
  id: '__root__' | '/' | '/api/products/expiring' | '/api/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiProductsExpiringRoute: typeof ApiProductsExpiringRoute
  ApiProductsIndexRoute: typeof ApiProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/': {
      id: '/api/products/'
      path: '/api/products'
      fullPath: '/api/products/'
      preLoaderRoute: typeof ApiProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/expiring': {
      id: '/api/products/expiring'
      path: '/api/products/expiring'
      fullPath: '/api/products/expiring'
      preLoaderRoute: typeof ApiProductsExpiringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiProductsExpiringRoute: ApiProductsExpiringRoute,
  ApiProductsIndexRoute: ApiProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
